#!/usr/bin/env python3
"""
Convert a BDF font file to a binary file using bdfconv.

Usage:
    python bdf2bin.py <bdf_file> -n <font_name> [options]

Example:
    python bdf2bin.py wenquanyi_13px.bdf -n u8g2_font_wenquanyi_13px -o output.bin
"""

import argparse
import codecs
import os
import re
import subprocess
import tempfile


def run_bdfconv(bdfconv_exe, bdf_file, font_name, char_range, output_c_file, verbose=False):
    """Invoke bdfconv to generate a C file from the BDF font."""
    if(os.path.exists(char_range) and ".map" in char_range):
        cmd = [bdfconv_exe, '-f', '1', '-M', char_range, bdf_file, '-o', output_c_file, '-n', font_name]
    else:
        cmd = [bdfconv_exe, '-f', '1', '-m', char_range, bdf_file, '-o', output_c_file, '-n', font_name]
    if verbose:
        cmd.insert(1, '-v')  # put -v after the executable
        print("Running:", ' '.join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"bdfconv failed:\n{result.stderr}")
    if verbose:
        print(result.stdout)
        print(result.stderr)


def extract_font_data(c_file_path, array_name):
    """
    Parse the C file generated by bdfconv and extract the binary data
    from the uint8_t array with the given name.
    """
    with open(c_file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Locate the array definition.
    # Pattern: const uint8_t array_name[ ... ] ... = ...
    pattern = re.compile(
        r'const\s+uint8_t\s+' + re.escape(array_name) +
        r'\s*\[\s*\d*\s*\]\s*(?:U8G2_FONT_SECTION\s*\(\s*"[^"]*"\s*\))?\s*=\s*',
        re.DOTALL
    )
    match = pattern.search(content)
    if not match:
        raise ValueError(f"Array '{array_name}' not found in C file")

    # Start parsing after the '=' sign.
    pos = match.end()
    length = len(content)
    in_string = False
    escape = False
    strings = []
    current = []

    i = pos
    while i < length:
        ch = content[i]
        if not in_string:
            if ch == '"':
                in_string = True
                i += 1
                continue
            elif ch == ';':
                # End of initializer
                break
            else:
                i += 1
                continue
        else:
            # Inside a string literal
            if ch == '\\' and not escape:
                escape = True
                current.append(ch)
                i += 1
                continue
            elif ch == '"' and not escape:
                # End of this string literal
                in_string = False
                strings.append(''.join(current))
                current = []
                i += 1
                continue
            else:
                current.append(ch)
                if escape:
                    escape = False
                i += 1
                continue

    if in_string:
        raise ValueError("Unterminated string literal in C file")

    # Concatenate all string literal contents
    combined = ''.join(strings)

    # Decode C-style escape sequences (octal, hex, and standard escapes)
    # Encode to ASCII bytes first (the string contains only ASCII)
    raw_bytes = combined.encode('ascii')
    decoded_bytes, _ = codecs.escape_decode(raw_bytes)

    return decoded_bytes


def main():
    parser = argparse.ArgumentParser(
        description='Convert a BDF font file to a binary file using bdfconv.'
    )
    parser.add_argument('bdf_file', help='Input BDF file path')
    parser.add_argument('-o', '--output', help='Output binary file path (default: <bdf_file>.bin)')
    parser.add_argument('-n', '--font-name', required=True,
                        help='Font name for bdfconv -n option (must match the name used in the generated C file)')
    parser.add_argument('-m', '--map', default='32-127',
                        help='Character map range (default: 32-127)')
    parser.add_argument('--bdfconv', default='./bdfconv.exe',
                        help='Path to bdfconv executable (default: ./bdfconv.exe)')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Print verbose output from bdfconv')
    parser.add_argument('--keep-c', action='store_true',
                        help='Keep the intermediate C file (default: delete it)')
    args = parser.parse_args()

    # Determine output binary file name
    if args.output:
        bin_file = args.output
    else:
        bin_file = os.path.splitext(args.bdf_file)[0] + '.bin'

    # Create a temporary C file (or a persistent one if --keep-c is used)
    if args.keep_c:
        c_file = os.path.splitext(bin_file)[0] + '.c'
        # Avoid accidental overwrite? Simple approach: just use the name.
    else:
        temp = tempfile.NamedTemporaryFile(mode='w', suffix='.c', delete=False)
        c_file = temp.name
        temp.close()

    #try:
        # Step 1: Run bdfconv to generate the C file
        run_bdfconv(args.bdfconv, args.bdf_file, args.font_name,
                    args.map, c_file, args.verbose)

        # Step 2: Extract binary data from the C file
        font_data = extract_font_data(c_file, args.font_name)

        # Step 3: Write the binary data to the output file
        with open(bin_file, 'wb') as f:
            f.write(font_data)

        if args.verbose:
            print(f"Extracted {len(font_data)} bytes, written to {bin_file}")

    #finally:
        # Clean up the intermediate C file unless --keep-c was given
    #    if not args.keep_c and os.path.exists(c_file):
    #        os.unlink(c_file)


if __name__ == '__main__':
    main()